//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien5ToT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUONG_TRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUONG_TRINH()
        {
            this.THAMGIA_CHUONGTRINH = new HashSet<THAMGIA_CHUONGTRINH>();
        }
    
        public int MaChuongTrinh { get; set; }
        public string TenChuongTrinh { get; set; }
        public Nullable<int> MaTieuChuan { get; set; }
        public Nullable<System.DateTime> ThoiGianDienRa { get; set; }
        public string DonViToChuc { get; set; }
        public string MoTa { get; set; }
        public string LinkBaiDang { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
        public virtual TIEU_CHUAN TIEU_CHUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA_CHUONGTRINH> THAMGIA_CHUONGTRINH { get; set; }
    }
}
