//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien5ToT
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public string Mssv { get; set; }
        public int MaLoaiDiem { get; set; }
        public Nullable<int> Diem1 { get; set; }
        public int MaHocKy { get; set; }
    
        public virtual HOCKY_XETDIEM HOCKY_XETDIEM { get; set; }
        public virtual LOAI_DIEM LOAI_DIEM { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
