//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien5ToT
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int IDnv { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDuser { get; set; }
        public string DonVi { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
        public virtual USER USER { get; set; }
    }
}
