//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien5ToT
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH_DIEM
    {
        public int MaQuyDinhDiem { get; set; }
        public Nullable<int> MaLoaiDiem { get; set; }
        public Nullable<int> DiemToiThieu { get; set; }
        public string MaDonVi { get; set; }
        public Nullable<int> MaTieuChuan { get; set; }
        public Nullable<int> Mathoigian { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
        public virtual LOAI_DIEM LOAI_DIEM { get; set; }
        public virtual TIEU_CHUAN TIEU_CHUAN { get; set; }
        public virtual THOIGIAN_XET THOIGIAN_XET { get; set; }
    }
}
