//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien5ToT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIEU_CHUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIEU_CHUAN()
        {
            this.CHUONG_TRINH = new HashSet<CHUONG_TRINH>();
            this.QUYDINH_DIEM = new HashSet<QUYDINH_DIEM>();
            this.THUCHIEN_TIEUCHUAN = new HashSet<THUCHIEN_TIEUCHUAN>();
        }
    
        public int MaTieuChuan { get; set; }
        public string TenTieuChuan { get; set; }
        public string MaTieuChi { get; set; }
        public Nullable<bool> MaLoaiTieuChuan { get; set; }
        public Nullable<int> Cap { get; set; }
        public Nullable<bool> QuyDinhGiai { get; set; }
    
        public virtual CAP_TIEU_CHUAN CAP_TIEU_CHUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUONG_TRINH> CHUONG_TRINH { get; set; }
        public virtual LOAI_TIEU_CHUAN LOAI_TIEU_CHUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYDINH_DIEM> QUYDINH_DIEM { get; set; }
        public virtual TIEU_CHI TIEU_CHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCHIEN_TIEUCHUAN> THUCHIEN_TIEUCHUAN { get; set; }
    }
}
